spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.111:33306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=15000
    username: root
    password: mysql
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      auto-commit: true

